# Generated by Django 4.0.1 on 2022-03-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='profile_images/')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('latest_chosen_service', models.CharField(blank=True, max_length=250, null=True)),
                ('last_contact_time', models.DateTimeField()),
                ('subscription', models.DateTimeField()),
                ('source_id', models.IntegerField()),
            ],
        ),
    ]
