# Generated by Django 4.0.1 on 2022-03-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, max_length=250, null=True)),
                ('user_name', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=1010, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='last_contact_time',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='subscription',
        ),
    ]
