# Generated by Django 4.0.1 on 2022-03-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_comments_remove_contacts_last_contact_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='sender_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
