# Generated by Django 4.0.1 on 2022-03-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contacts_sender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
