# Generated by Django 4.0.1 on 2022-03-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_comments_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
