# Generated by Django 4.0.1 on 2022-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
