# Generated by Django 4.0 on 2022-04-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_commentauthors_alter_comments_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='commentauthors',
            name='user_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
